/* Course content is independent of rendering and database execution.
   Stable section and step IDs are used for links and saved progress. */
window.COURSE = {
  title: 'Database Administration & Security',
  units: [
    { id: 'u1', title: 'DBMS fundamentals', status: 'ready', hours: 10 },
    { id: 'u2', title: 'SQL', status: 'planned', hours: 10 },
    { id: 'u3', title: 'Security & administration', status: 'planned', hours: 10 },
    { id: 'u4', title: 'Monitoring & recovery', status: 'planned', hours: 10 }
  ],
  sections: [
    {
      id: 'why', number: '1.1', title: 'Why databases exist', minutes: 60,
      objective: 'Explain what a DBMS helps us manage beyond simply storing data.',
      steps: [
        { id: 'college-problem', title: 'One college. Thousands of facts.', lead: 'Names, courses, attendance, marks and fees. Start with a familiar question: where would you keep all of this?', type: 'cards', cards: [['5,000 students', 'Each has contact details, a course and a history of changes.'], ['Multiple teams', 'Admissions, teachers and accounts all need different parts of the data.'], ['Every day', 'People join, change courses, pay fees and correct mistakes.']], question: 'Could we put everything in a spreadsheet? What would become difficult?', answer: 'Yes, a small spreadsheet may work well. As the number of users and relationships grows, keeping copies consistent, controlling access and recovering changes becomes harder.', notes: 'Collect answers before introducing the term DBMS. Avoid claiming spreadsheets cannot manage data. Ask what changes when three departments edit copies.' },
        { id: 'conflicting-copies', title: 'Which copy tells the truth?', lead: 'These are three copies of the same course name. Change one and watch the others fall behind.', type: 'copies', question: 'Has the college changed its course name, or only one file?', answer: 'Only one copy changed. Repetition makes it easy for copies to disagree. A shared course record can reduce this duplication.', notes: 'Click Update admissions copy. Point at the conflicting names. Then click Use a shared course record. This is a conceptual illustration, not a live SQL operation.' },
        { id: 'file-vs-dbms', title: 'Turn problems into responsibilities.', lead: 'A DBMS provides mechanisms. A good design and sensible configuration make those mechanisms useful.', type: 'comparison', columns: ['Problem', 'File-based workflow', 'DBMS support'], rows: [['Repeated facts', 'Update every copy correctly', 'Related tables and shared identifiers'], ['Invalid values', 'Depend on each person checking', 'Types, constraints and transactions'], ['Several editors', 'Coordinate versions and edits', 'Concurrency control and isolation'], ['Different access', 'Manage access to whole files', 'Users, roles and privileges'], ['Accidental loss', 'Recover a saved copy if one exists', 'Backup and recovery tools']], question: 'Does using a DBMS guarantee there will never be incorrect data?', answer: 'No. A missing rule, an overpowered account or an untested backup can still cause problems.', notes: 'Ask students which row affects admissions most, then which affects an administrator most.' },
        { id: 'concurrent-edit', title: 'Two people can act on the same fact.', lead: 'A course has one seat left. Two users read “1” before either completes an enrollment.', type: 'timeline', items: [['Read', 'Both users see one available seat.'], ['Decide', 'Both decide they can enroll a student.'], ['Write', 'Without appropriate coordination, the system may accept both.'], ['Coordinate', 'A transaction and suitable locking or validation can enforce the capacity rule.']], question: 'Would using two different computers solve this?', answer: 'No. The shared data and the timing of the operations are the issue. The database needs a correctly designed concurrency strategy.', notes: 'Keep this as motivation. Detailed isolation and locks belong later in the course.' },
        { id: 'why-check', title: 'Checkpoint: diagnose a broken record system.', lead: 'Accounts sees a paid fee. Admissions sees it as unpaid. A teacher can also edit bank details.', type: 'quiz', options: ['A storage-capacity problem only', 'Inconsistency and excessive access', 'A primary-key problem only'], correct: 1, feedback: 'The two copies disagree, and the teacher has permissions beyond the teaching role.', question: 'Student task: name one additional failure and the mechanism you would want.', answer: 'Example: a file is accidentally deleted → recoverable backups. A student is entered twice → a well-chosen key or uniqueness rule.', notes: 'Recap: storage is only part of the problem. Management includes correctness, shared access, protection and recovery.' }
      ]
    },
    {
      id: 'vocabulary', number: '1.2', title: 'Database, DBMS & people', minutes: 45,
      objective: 'Distinguish the data, the management software, the client and the people responsible.',
      steps: [
        { id: 'database-vs-dbms', title: 'The data and its manager are different.', lead: 'Use the college lab to attach every term to something concrete.', type: 'cards', cards: [['Database', 'college_demo: the organized student, course and enrollment data.'], ['DBMS', 'MariaDB Server: the software that stores data and enforces database operations.'], ['Client', 'Adminer or the teacher console: an interface that sends requests and shows results.']], question: 'If you close Adminer, have you deleted the database?', answer: 'No. The server and its stored data have a separate lifecycle from the client window.', notes: 'Open Adminer if useful, then return here. The console now sends actual lesson queries to MariaDB through a small service.' },
        { id: 'people', title: 'Different people need different capabilities.', lead: 'Responsibility determines what someone needs to do with the database.', type: 'comparison', columns: ['Person', 'Typical work', 'Access needed'], rows: [['Student', 'View their own results', 'Approved records through an application'], ['Application developer', 'Build enrollment workflows', 'Development access appropriate to the role'], ['Analyst', 'Summarize course demand', 'Read approved reporting data'], ['DBA', 'Manage access, availability and recovery', 'Administrative privileges appropriate to the task']], question: 'Should every person receive the same database account?', answer: 'No. Accounts and permissions should reflect responsibilities. Some people only access data through an application and never receive a direct database login.', notes: 'Separate application users from database users. A website may use a database service account on behalf of many students.' },
        { id: 'data-shapes', title: 'Data can have different kinds of structure.', lead: 'A fixed table is one way to organize facts; a document can carry its own named fields.', type: 'comparison', columns: ['Form', 'College example', 'Shape'], rows: [['Structured', 'A student row: id, name, age', 'A defined set of typed columns'], ['Semi-structured', '{"student_id": 1, "interests": ["SQL", "Linux"]}', 'Named fields with flexible or nested structure'], ['Unstructured', 'A scanned handwritten feedback sheet', 'The content is not already arranged as database fields']], question: 'Is a JSON document the same thing as a relational table?', answer: 'No. Both can represent organized information, but their structure and querying model differ. A relational DBMS may also provide JSON features.', notes: 'Avoid framing these as mutually exclusive database products. Discuss the shape of the data first.' },
        { id: 'vocabulary-check', title: 'Checkpoint: identify the manager.', lead: 'You use Adminer in a browser to read students from college_demo, which is stored by MariaDB.', type: 'quiz', options: ['The browser is the DBMS', 'college_demo is the DBMS', 'MariaDB Server is the DBMS'], correct: 2, feedback: 'MariaDB Server manages the database. Adminer is a client, and college_demo is the database.', question: 'Student task: explain all three terms without using the word “SQL.”', answer: 'Database: an organized collection of data. DBMS: software that manages databases. Client: an interface through which a user or application requests operations.', notes: 'Recap by having a student point to each layer on the next architecture lesson, or sketch it on the board.' }
      ]
    },
    {
      id: 'tables', number: '1.3', title: 'Tables, rows & columns', minutes: 75,
      objective: 'Read a relational table and explain its rows, attributes, domains and NULL values.',
      steps: [
        { id: 'explore-table', title: 'A table gives related facts a shape.', lead: 'These records come from the MariaDB lab. Click a column heading or a row to make it the focus.', type: 'explorer', table: 'students', question: 'What does one row represent? What does the age column represent?', answer: 'One row is one student record. age is one attribute recorded for students; its values come from a defined domain.', notes: 'Switch to courses and ask the same questions. Use Highlight row / column through the table itself. course_id means primary course in this teaching model.' },
        { id: 'relational-words', title: 'Same ideas, two vocabularies.', lead: 'Relational theory and everyday SQL language describe related concepts.', type: 'comparison', columns: ['Everyday term', 'Relational term', 'Example'], rows: [['Table', 'Relation', 'students'], ['Row / record', 'Tuple', 'The record for student 1'], ['Column / field', 'Attribute', 'email'], ['Allowed values', 'Domain', 'Permitted ages and email representations']], question: 'Is the third visible row guaranteed to stay in the third position?', answer: 'No. A query needs ORDER BY when a particular result order matters. An identifier is more reliable than a screen position.', notes: 'Note that SQL tables and relational theory are not identical in every detail; SQL permits NULL and, without constraints, duplicate rows.' },
        { id: 'domains', title: 'A value needs to fit the column.', lead: 'A data type controls representation. Constraints add rules that the type alone does not express.', type: 'comparison', columns: ['Column', 'Type', 'Additional rule'], rows: [['id', 'INT', 'Primary key: unique and not NULL'], ['name', 'VARCHAR(100)', 'NOT NULL; other validation may still be needed'], ['email', 'VARCHAR(120)', 'UNIQUE and NOT NULL in this lab'], ['age', 'INT', 'CHECK age >= 16; NULL is allowed'], ['course_id', 'INT', 'Must refer to an existing course, or be NULL']], question: 'Does VARCHAR(120) prove an email address is valid?', answer: 'No. It limits representation and length. Email-format validation is a separate rule.', notes: 'Use the actual students definition in the following real-query step to anchor this table.' },
        { id: 'null', title: 'NULL means an absent value.', lead: 'Unknown age is different from age zero. An absent email is different from the empty string.', type: 'cards', cards: [['NULL', 'The value is missing, unknown or not applicable. The schema may permit it.'], ['0', 'A known numeric value of zero. It is still a value.'], ["''", 'A known text value with no characters. It is not NULL.']], question: 'Would age = NULL correctly find students with a missing age?', answer: 'Use age IS NULL. Comparisons such as age = NULL evaluate to unknown rather than true.', notes: 'A CHECK such as age >= 16 does not by itself ban NULL. A separate NOT NULL rule would be needed.' },
        { id: 'inspect-schema', title: 'Ask MariaDB about the table.', lead: 'The server can describe a table even before you learn how to create one.', type: 'query', database: 'college_demo', sql: 'DESCRIBE students;', expected: 'Five columns. id is the primary key; email is unique; age and course_id permit NULL.', question: 'Which parts describe the shape, rather than the current student values?', answer: 'Field, Type, Null, Key, Default and Extra describe the table definition. They are metadata.', notes: 'Run the query, then point to each relevant result field. Explain AUTO_INCREMENT briefly if students notice Extra.' },
        { id: 'tables-check', title: 'Checkpoint: explain one student record.', lead: 'Ask a student to identify the relation, a tuple, two attributes and one domain rule in the live table.', type: 'quiz', options: ['A row is one attribute across all students', 'A column stores the entire database', 'A row represents one student record'], correct: 2, feedback: 'A student row groups values about one student; columns describe attributes shared across the table.', question: 'Student task: design three columns for a library book table and choose sensible types.', answer: 'One possible design: book_id INT, title VARCHAR(200), published_year INT. State the meaning of each row and any additional rules; there is more than one valid design.', notes: 'Recap: shape, allowed values and missing values. Ask why publication year alone should not identify a book.' }
      ]
    },
    {
      id: 'keys', number: '1.4', title: 'Keys & integrity', minutes: 75,
      objective: 'Choose identifiers and explain how constraints protect data integrity.',
      steps: [
        { id: 'names-not-ids', title: 'Two students can have the same name.', lead: 'A name helps a person recognize someone. A key helps the database identify a record unambiguously.', type: 'comparison', columns: ['id', 'name', 'email'], rows: [[21, 'Riya Sharma', 'riya21@example.com'], [37, 'Riya Sharma', 'riya37@example.com']], question: 'If someone says “update Riya Sharma,” which record should change?', answer: 'The instruction is ambiguous. A stable unique identifier such as id = 21 selects the intended record.', notes: 'Ask about name changes and spelling corrections. Neither should accidentally change the identity of a student.' },
        { id: 'key-family', title: 'Keys have different jobs.', lead: 'Choose a minimal unique identifier, then use references to connect it to other tables.', type: 'comparison', columns: ['Key', 'Meaning', 'Example'], rows: [['Candidate', 'A minimal set of attributes that can uniquely identify a row', 'id, or a mandatory unique email under an explicit policy'], ['Primary', 'The chosen candidate identifier', 'students.id'], ['Alternate', 'A candidate key not chosen as primary', 'students.email in this lab'], ['Composite', 'A key made of multiple attributes', '(student_id, course_id) for one enrollment per course'], ['Foreign', 'A reference to a key in another or the same table', 'students.course_id → courses.id']], question: 'Can two students share the same foreign-key value?', answer: 'Yes. Several students may reference course 101. A foreign key does not imply uniqueness in the referencing table.', notes: 'A composite key is not automatically a primary key. Our enrollment pair is UNIQUE, with a separate id primary key.' },
        { id: 'integrity-demo', title: 'Will this proposed record be accepted?', lead: 'Try three candidate records against the displayed rules. This illustration does not change the database.', type: 'integrity', question: 'Why is each rejected record a different kind of problem?', answer: 'The duplicate ID violates identity. The missing course violates referential integrity. The valid candidate satisfies the illustrated rules.', notes: 'Ask students to predict before choosing each example. MariaDB may report additional errors if a record violates more than one rule.' },
        { id: 'integrity-rules', title: 'Protect identity, references and values.', lead: 'Different constraints guard different promises.', type: 'cards', cards: [['Entity integrity', 'Every primary-key value identifies one row and cannot be NULL.'], ['Referential integrity', 'A non-NULL foreign-key value must refer to an allowed existing key.'], ['Domain rules', 'Types and constraints limit values: for example, an age must be at least 16 when supplied.']], question: 'Can a valid course be deleted while students still refer to it?', answer: 'It depends on the defined referential action. This lab uses ON DELETE SET NULL for students.course_id, while enrollment references restrict deleting courses that still have enrollment rows.', notes: 'Do not delete the seeded courses during this theory step. Explain RESTRICT, CASCADE and SET NULL conceptually; detailed SQL comes later.' },
        { id: 'keys-check', title: 'Checkpoint: one enrollment, two identifiers.', lead: 'A student may take several courses. The same student should not be enrolled in the same course twice.', type: 'quiz', options: ['Make student_id unique by itself', 'Make (student_id, course_id) unique together', 'Make course_id unique by itself'], correct: 1, feedback: 'The pair prevents duplicate enrollments while allowing a student to take several courses and a course to have several students.', question: 'Student task: identify the foreign keys and the candidate key in this example.', answer: 'student_id and course_id are foreign keys to their respective tables. Together they form a candidate key under the one-enrollment-per-course rule; an enrollment id can be another candidate.', notes: 'Recap identity, uniqueness and references. Have students explain why both individual UNIQUE proposals fail.' }
      ]
    },
    {
      id: 'relationships', number: '1.5', title: 'Relationships', minutes: 75,
      objective: 'Trace one-to-one, one-to-many and many-to-many relationships using keys.',
      steps: [
        { id: 'cardinality', title: 'How many records may be related?', lead: 'Cardinality is a statement about the rules of the system, not just the rows visible today.', type: 'cards', cards: [['One to one', 'A student and their optional profile: at most one profile per student, if student_id is unique in profiles.'], ['One to many', 'A course may be the primary course of many students. Each student has at most one primary course here.'], ['Many to many', 'A student may take many courses; a course may have many students. Use enrollments to record the pairs.']], question: 'If a course currently has one student, is its relationship necessarily one-to-one?', answer: 'No. Current data is an instance. The allowed relationship is determined by the model and its constraints.', notes: 'Mention optionality: “one” may be zero or one when a relationship is optional. Our primary-course field allows NULL.' },
        { id: 'trace-primary-course', title: 'Follow a primary-course ID.', lead: 'Choose a course to see the students whose primary course points to it.', type: 'relationship', mode: 'primary', question: 'Where would you change the displayed course name?', answer: 'Change it in courses. Related query results can then show the new name through the shared ID.', notes: 'The physical column is students.course_id. We use it specifically for primary course; enrollments separately records all courses taken.' },
        { id: 'trace-enrollments', title: 'One student can take several courses.', lead: 'Choose a student. Follow each enrollment from student_id to course_id.', type: 'relationship', mode: 'enrollments', question: 'Why does Aman appear in two enrollment records?', answer: 'Aman takes Cybersecurity and Python for Security. The student identity appears once in students, while each enrollment records a separate relationship.', notes: 'Choose Meera to show zero enrollment rows. A primary-course assignment does not automatically create an enrollment. Discuss whether the application should enforce that policy.' },
        { id: 'joined-view', title: 'Bring connected facts into one result.', lead: 'The stored tables keep responsibilities separate. A query combines the facts needed for an answer.', type: 'query', database: 'college_demo', sql: 'SELECT s.name, c.course_name AS primary_course\nFROM students AS s\nJOIN courses AS c ON s.course_id = c.id\nORDER BY s.id;', expected: 'Five student names paired with their primary course names.', question: 'Did this query merge the stored tables permanently?', answer: 'No. It produced a result from matching rows. students and courses remain separate tables.', notes: 'Point to the two matching ID columns. Do not turn this into a full JOIN syntax lesson; that belongs in Unit 2.' },
        { id: 'relationships-check', title: 'Checkpoint: model a library loan.', lead: 'A reader can borrow several books, and a book can be borrowed by different readers over time.', type: 'quiz', options: ['Store a comma-separated list of book IDs inside the reader name', 'Record each loan in a separate loans table', 'Give every book the same reader ID forever'], correct: 1, feedback: 'A loans table records each borrowing event, including its reader, book and dates.', question: 'Student task: propose columns and explain whether (reader_id, book_id) alone should be unique.', answer: 'loan_id, reader_id, book_id, borrowed_on and returned_on are a reasonable start. A reader may borrow the same book again, so the pair alone should not normally be unique across all history.', notes: 'Recap: relationships follow business rules. Contrast repeated library loans with the simplified enrollment rule.' }
      ]
    },
    {
      id: 'abstraction', number: '1.6', title: 'Schema & abstraction', minutes: 60,
      objective: 'Distinguish schema from instance and explain abstraction and data independence.',
      steps: [
        { id: 'schema-instance', title: 'The structure can stay while the contents change.', lead: 'A table definition is its schema. The records present at a particular moment form its instance.', type: 'schema-instance', question: 'When we add a student, which one changes?', answer: 'The instance changes. The schema changes only if we alter the definition, such as adding a column or changing a constraint.', notes: 'Use Add illustrative row, then Toggle schema change. These are visual examples and do not alter MariaDB.' },
        { id: 'three-levels', title: 'One system, three levels of description.', lead: 'Switch levels to see what each audience needs to understand.', type: 'layers', question: 'Does a teacher need to know which disk page contains a student record?', answer: 'Usually not. An external view can expose the needed facts while physical storage details remain hidden.', notes: 'External: user-specific views. Conceptual: the overall logical structure. Internal: storage representation. These levels are conceptual; they need not be three separate programs.' },
        { id: 'physical-independence', title: 'Change how data is stored.', lead: 'An administrator adds an index to make a lookup more efficient.', type: 'comparison', columns: ['Before', 'Internal change', 'After'], rows: [['SELECT name FROM students WHERE id = 1;', 'Change an access path or physical storage organization', 'The same logical query still requests the same student name']], question: 'Should adding an index force every application to learn a new student identifier?', answer: 'No. Physical data independence means storage changes can often occur without changing the conceptual schema or application queries.', notes: 'This is a conceptual example, not a benchmark. The id already has an index because it is a primary key; discuss adding indexes on other lookup fields if needed.' },
        { id: 'logical-independence', title: 'Change structure while preserving an interface.', lead: 'Suppose a single student table is split into student and contact tables.', type: 'timeline', items: [['Old interface', 'A report reads student_id, name and email.'], ['New logical model', 'Contact details move into a related contacts table.'], ['Compatibility view', 'A view can expose the old report columns by joining the new tables.'], ['Practical limit', 'Some changes still require application changes; compatible reads do not guarantee compatible writes.']], question: 'Is logical data independence as easy to achieve as physical independence?', answer: 'Often no. Applications rely on logical meanings and structures. Views can help preserve interfaces, but cannot hide every semantic change.', notes: 'Use the idea of a familiar shopfront over a reorganized storeroom only if helpful; keep the database example primary.' },
        { id: 'abstraction-check', title: 'Checkpoint: what changed?', lead: 'A new student joins; a new date-of-birth column is added; a secondary index is created.', type: 'quiz', options: ['Instance, logical schema, physical access structure', 'Physical storage, instance, student identity', 'All three are just new rows'], correct: 0, feedback: 'Inserting changes current data; adding a column changes the logical schema; adding an index changes an access structure without changing the logical row contents.', question: 'Student task: give one external view for accounts and another for a teacher.', answer: 'Accounts may need student ID and payment status. A teacher may need a class roster and marks. Neither role necessarily needs all student attributes.', notes: 'Recap schema/instance and the external/conceptual/internal levels. Distinguish conceptual three-schema architecture from application tiers in the next section.' }
      ]
    },
    {
      id: 'architecture', number: '1.7', title: 'Architecture & queries', minutes: 60,
      objective: 'Locate clients, server and storage, and trace a query through the system.',
      steps: [
        { id: 'our-lab', title: 'Meet the parts of your running lab.', lead: 'These are separate responsibilities even though Docker runs them on one computer.', type: 'timeline', items: [['Browser', 'Displays this console or Adminer.'], ['Client / service', 'Formats a request and connects with a database account.'], ['MariaDB Server', 'Executes SQL and applies permissions, constraints and transaction rules.'], ['Docker volume', 'Holds the database files across ordinary container restarts.']], question: 'If the browser closes, which part still holds the student records?', answer: 'The database files remain in the Docker volume, and MariaDB can continue running independently of that browser window.', notes: 'Point out the practical distinction between closing a browser, stopping a container and deleting a volume. Do not delete volumes to demonstrate it.' },
        { id: 'tiers', title: 'A tier describes where application work happens.', lead: 'Application tiers and the three-schema model answer different questions.', type: 'comparison', columns: ['Arrangement', 'Typical path', 'What to notice'], rows: [['One tier', 'Application with a local embedded database', 'Processing is local to one environment'], ['Two tier', 'Database client → database server', 'Client talks directly to the database service'], ['Three tier', 'Browser → application service → database server', 'Application logic mediates database requests']], question: 'Which path does this teacher console use for its live queries?', answer: 'Browser → classroom service → MariaDB: a three-tier application path. Adminer also runs server-side PHP between the browser and database.', notes: 'A command-line MariaDB client connecting directly to MariaDB is a clear two-tier example. Do not label Adminer as a direct browser-to-database connection.' },
        { id: 'query-journey', title: 'Follow one query from request to result.', lead: 'Advance the highlight to trace SELECT name FROM students WHERE id = 1.', type: 'pipeline', question: 'Where does SQL become an execution strategy?', answer: 'The optimizer/planning stage selects an execution strategy. Execution uses the storage engine and may use cached pages rather than reading disk every time.', notes: 'This is a simplified conceptual journey, not an exact ordering of every internal check. Mention privileges and name resolution without claiming they happen at only one point.' },
        { id: 'real-request', title: 'Send the query you just traced.', lead: 'This request executes in the MariaDB container and returns a real result.', type: 'query', database: 'college_demo', sql: 'SELECT id, name\nFROM students\nWHERE id = 1;', expected: 'One row: student 1, Aman Verma, in the original seed data.', question: 'Did the browser need to understand MariaDB’s on-disk page format?', answer: 'No. The client sends SQL through a database connection and receives structured results. Storage is the server’s responsibility.', notes: 'If seed data was changed in Adminer, explain the actual observed result rather than promising the initial name.' },
        { id: 'architecture-check', title: 'Checkpoint: locate a failure.', lead: 'The console loads, but a query reports that the database connection is unavailable.', type: 'quiz', options: ['The table must have no rows', 'Inspect the service, database readiness and connection path', 'The browser must be unable to display text'], correct: 1, feedback: 'A loaded page proves the web page was served. It does not prove that the database connection is ready.', question: 'Student task: draw the path from a button click to a stored record and back.', answer: 'Browser → classroom service → MariaDB → storage or cache → MariaDB result → service response → browser table.', notes: 'Recap clients, server, storage, tiers and the query journey. This sets up the real practical next.' }
      ]
    },
    {
      id: 'practical', number: '1.8', title: 'First MariaDB practical', minutes: 90,
      objective: 'Inspect a real database, create a table, insert records and retrieve selected data.',
      steps: [
        { id: 'lab-start', title: 'The database is ready. Start exploring.', lead: 'college_demo contains the prepared teaching data. classroom_practice is your separate workspace for this lab.', type: 'query', database: 'college_demo', sql: 'SHOW DATABASES;', expected: 'Databases visible to this console account, including college_demo and classroom_practice. Visibility depends on privileges.', question: 'Why might root see more databases than this account?', answer: 'SHOW DATABASES is affected by database privileges. This console uses a limited account; root has broader visibility.', notes: 'All queries use real MariaDB. Each request opens a fresh connection. The database selector is the console equivalent of choosing a default database with USE; demonstrate USE in Adminer or a persistent CLI session.' },
        { id: 'lab-tables', title: 'Inspect what already exists.', lead: 'Start with names, then inspect a definition. No need to build the examples from scratch.', type: 'query', database: 'college_demo', sql: 'SHOW TABLES;', presets: [['Table names', 'SHOW TABLES;'], ['Student definition', 'DESCRIBE students;'], ['Course data', 'SELECT * FROM courses ORDER BY id;']], expected: 'Three base tables plus student_course_summary, a view.', question: 'Why does SHOW TABLES include student_course_summary?', answer: 'MariaDB includes views in this listing. A view defines a query-based interface; it is not another separately seeded copy of those student-course rows.', notes: 'Click each prepared query. DESCRIBE shows column metadata, while SELECT shows records.' },
        { id: 'lab-create', title: 'Create your first practice table.', lead: 'Define the columns and their rules. This table is separate from the prepared college data.', type: 'query', database: 'classroom_practice', sql: 'CREATE TABLE lab_students (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  name VARCHAR(100) NOT NULL,\n  email VARCHAR(120) NOT NULL UNIQUE,\n  age INT CHECK (age >= 16)\n);', expected: 'Statement completed. Creating the table does not insert any student rows.', question: 'What will MariaDB generate automatically when we omit id?', answer: 'AUTO_INCREMENT generates an ID. PRIMARY KEY makes it unique and non-NULL. Generated IDs can have gaps and are not a row count.', notes: 'For a repeat lecture use Reset lab_students, then run CREATE again. If the table already exists, the server error is accurate. Reset affects only this practice table.' },
        { id: 'lab-insert', title: 'Add the records the table will hold.', lead: 'Read the column list, then match each supplied value to its column.', type: 'query', database: 'classroom_practice', setup: true, sql: "INSERT INTO lab_students (name, email, age)\nVALUES ('Aman', 'aman.lab@example.com', 25),\n       ('Riya', 'riya.lab@example.com', 19),\n       ('Kabir', 'kabir.lab@example.com', 22);", expected: 'Three rows inserted on the first run. Repeating it should fail because these emails are unique.', question: 'Why does the statement omit the id column?', answer: 'MariaDB generates the ID because the column uses AUTO_INCREMENT.', notes: 'If jumping here directly, Prepare example creates the table only. It does not insert rows on this step. Duplicate-email errors on a repeated run are useful demonstrations.' },
        { id: 'lab-select', title: 'Ask for all rows, then fewer columns.', lead: 'The question determines the shape of the result.', type: 'query', database: 'classroom_practice', setup: true, seedPractice: true, sql: 'SELECT * FROM lab_students ORDER BY id;', presets: [['All columns', 'SELECT * FROM lab_students ORDER BY id;'], ['Name and age', 'SELECT name, age FROM lab_students ORDER BY id;']], expected: 'The sample has three rows. Selecting name and age returns two columns without removing other columns from storage.', question: 'Does SELECT name, age delete the email column?', answer: 'No. It selects columns in the result. The stored table is unchanged.', notes: 'Prepare example can create the table and add any missing sample emails if this step was opened directly. It preserves other practice rows.' },
        { id: 'lab-filter', title: 'Return only the rows that match.', lead: 'Predict who will remain when the condition is age > 20.', type: 'query', database: 'classroom_practice', setup: true, seedPractice: true, sql: 'SELECT name, age\nFROM lab_students\nWHERE age > 20\nORDER BY age;', expected: 'In the sample: Kabir (22), then Aman (25). Riya (19) does not match.', question: 'Would age >= 20 include a student aged exactly 20?', answer: 'Yes. > is strictly greater than; >= includes equality. A NULL age does not make either condition true.', notes: 'Change the threshold live or ask a student to propose a condition. Extra practice rows may also appear if they match.' },
        { id: 'lab-constraints', title: 'A real database can reject a record.', lead: 'Choose a proposed insert. Predict the outcome, then read the actual MariaDB message.', type: 'query', database: 'classroom_practice', setup: true, seedPractice: true, sql: "INSERT INTO lab_students (name, email, age)\nVALUES ('Aman again', 'aman.lab@example.com', 25);", presets: [['Duplicate email', "INSERT INTO lab_students (name, email, age) VALUES ('Aman again', 'aman.lab@example.com', 25);"], ['Invalid age', "INSERT INTO lab_students (name, email, age) VALUES ('Young learner', 'young.lab@example.com', 12);"], ['Missing name', "INSERT INTO lab_students (name, email, age) VALUES (NULL, 'missing.lab@example.com', 21);"]], expected: 'Each supplied example intentionally violates a constraint and should produce an error.', question: 'Did the failure mean MariaDB broke?', answer: 'No. Rejecting a row that violates a declared rule is the intended behavior.', notes: 'Prepare example first when jumping here directly. Different errors reveal UNIQUE, CHECK and NOT NULL enforcement.' },
        { id: 'lab-challenge', title: 'Your turn: a course table.', lead: 'Create lab_courses with an automatically generated ID, a required name and a positive duration in months. Insert three courses and display them.', type: 'challenge', question: 'Write and run one statement at a time in the practice database.', answer: "CREATE TABLE lab_courses (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  course_name VARCHAR(100) NOT NULL,\n  duration_months INT NOT NULL CHECK (duration_months > 0)\n);\n\nINSERT INTO lab_courses (course_name, duration_months)\nVALUES ('Cybersecurity', 6), ('Databases', 4), ('Python', 3);\n\nSELECT * FROM lab_courses ORDER BY id;", notes: 'Let students derive this from lab_students. Use Open SQL workspace or Adminer to try their answer. lab_students reset does not remove lab_courses. Repeating CREATE on an existing table should report an error; inspect it or choose a new name.' },
        { id: 'lab-recap', title: 'You have completed the first database workflow.', lead: 'You inspected a database, defined a table, stored records and asked precise questions about them.', type: 'quiz', options: ['CREATE defines the structure; INSERT adds rows; SELECT retrieves results', 'SELECT creates a new table every time', 'INSERT changes the name of the database'], correct: 0, feedback: 'The workflow moves from a definition to stored records to query results. Each command has a different responsibility.', question: 'Student task: explain one error you encountered and the rule behind it.', answer: 'Examples: an existing table name, a duplicate unique email, an age below the CHECK threshold or a missing required name. A useful explanation links the server message to the rule.', notes: 'Recap rather than introduce more syntax. Unit 2 will cover modification, advanced filtering, aggregation and joins in depth.' }
      ]
    },
    {
      id: 'dba', number: '1.9', title: 'DBA & Unit 1 checkpoint', minutes: 60,
      objective: 'Connect DBA responsibilities to failure scenarios and demonstrate the Unit 1 fundamentals.',
      steps: [
        { id: 'dba-jobs', title: 'Who keeps the data service dependable?', lead: 'A DBA combines technical operations with decisions about access, correctness and recovery.', type: 'comparison', columns: ['Responsibility', 'College example', 'Evidence it is working'], rows: [['Access control', 'A reporting user cannot edit marks', 'Privileges inspected and denied actions tested'], ['Integrity', 'Enrollments refer to existing students', 'Constraints reject invalid records'], ['Availability', 'The service is ready when class starts', 'Health checks and operational monitoring'], ['Recovery', 'Accidental loss can be reversed', 'A backup is restored and verified'], ['Performance', 'A course roster loads promptly', 'Queries and resource use are measured']], question: 'Is taking a backup enough to prove we can recover?', answer: 'No. A restore must be tested and the recovered data checked. Recovery also depends on what was backed up and when.', notes: 'Tie each responsibility back to the initial file-storage problems. Save implementation details for Units 3 and 4.' },
        { id: 'least-privilege', title: 'Give each account the access it needs.', lead: 'A report reader does not normally need to delete tables or create database users.', type: 'cards', cards: [['Administrator', 'Manages server and access. Powerful privileges should be reserved for appropriate administrative work.'], ['Application account', 'Reads and changes only what its workflows require. The exact privileges depend on the application.'], ['Reporting account', 'Reads approved data and builds reports; usually has no data-modification privileges.']], question: 'Should a public website connect as root?', answer: 'Normally no. If the application is compromised or misbehaves, its database privileges determine the damage it can do. Apply least privilege.', notes: 'The console itself uses a limited account: SELECT on college_demo and practice-table privileges on classroom_practice.' },
        { id: 'incident', title: 'A teacher can see everyone’s fee details.', lead: 'The data is correct and the server is fast, but an account has more access than its role needs.', type: 'quiz', options: ['Add an index', 'Review authorization and limit exposed records or columns', 'Increase the student ID range'], correct: 1, feedback: 'Correctness and speed do not imply appropriate access. Review which account, view or application route exposes the information.', question: 'Student task: name four other incidents and the DBA responsibility each involves.', answer: 'Deleted records → recovery. Invalid references → integrity. Server unavailable → availability. A slow report → performance. Different incidents may involve several responsibilities.', notes: 'Ask students to distinguish authentication (“who are you?”) from authorization (“what may you do?”).' },
        { id: 'unit-challenge', title: 'Build a small, defensible college model.', lead: 'Work in pairs. Design students and courses, choose the keys, add sample records and describe who should be allowed to change them.', type: 'challenge', question: 'Include: two tables, a primary key per table, one relationship, a schema/instance explanation and one filtered query.', answer: 'A valid solution uses unique student/course IDs, a students.course_id reference for one primary course, and clear column rules. Schema means these definitions; instance means the current sample rows. Example retrieval: SELECT name FROM students WHERE age > 20. An analyst could receive read access; changing course assignments belongs to an appropriate application or staff role.', notes: 'Evaluate reasoning, not a single exact schema. Allow an enrollments table if they model multiple courses. Ask them to state assumptions and optionality.' },
        { id: 'unit-complete', title: 'Unit 1 complete. You can now read the system.', lead: 'You know what the parts mean, how records connect, and what the DBMS is responsible for.', type: 'cards', cards: [['Explain', 'Database vs DBMS vs client; schema vs instance; abstraction and architecture.'], ['Identify', 'Tables, rows, attributes, domains, keys and relationship types.'], ['Demonstrate', 'Inspect a real MariaDB table; create, insert and select; explain a constraint error.']], question: 'Exit ticket: explain a foreign key and name one thing a DBMS cannot guarantee without good design or configuration.', answer: 'A foreign key enforces allowed references to a key. A DBMS cannot guarantee an appropriate business rule, least-privilege access or a successful restore unless those are designed, configured and tested.', notes: 'Continue with Next to begin Unit 2 SQL, or choose it from Course contents. Units 3 and 4 remain planned. Review any Unit 1 section using the sidebar.' }
      ]
    }
  ]
};
